# Generated by Django 5.2 on 2025-05-01 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='probleme_projet',
        ),
        migrations.DeleteModel(
            name='Projet',
        ),
    ]
