# Generated by Django 5.0.6 on 2025-06-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nom',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
