# Generated by Django 5.0.6 on 2025-06-28 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_customuser_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalportefeuille',
            name='responsable',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 'gestionnaire'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='portefeuille',
            name='responsable',
            field=models.ForeignKey(limit_choices_to={'role': 'gestionnaire'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
