# Generated by Django 5.2 on 2025-05-01 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_delete_probleme_projet_delete_projet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Axe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Composante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=255)),
                ('localisation', models.CharField(max_length=255)),
                ('tutelle', models.CharField(max_length=255)),
                ('agence_execution', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('En cours', 'En cours'), ('Bloquée', 'Bloquée'), ('Terminée', 'Terminée'), ('Dépriorisée', 'Dépriorisée')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Portefeuille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('responsable', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=255)),
                ('est_synthese', models.BooleanField(default=False)),
                ('ponderation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('prev_t1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('prev_t2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('prev_t3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('prev_t4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cible_fin_annee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('realise_t1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('realise_t2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('realise_t3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('realise_t4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avancement_physique', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dec_prev_t1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dec_prev_t2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dec_prev_t3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dec_prev_t4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dec_cible', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dec_reel_t1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dec_reel_t2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dec_reel_t3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dec_reel_t4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('taux_decaissement', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('facteurs_explication', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, max_length=100, null=True)),
                ('feu_tricolore', models.CharField(blank=True, max_length=10, null=True)),
                ('execution_physique', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('execution_financiere', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('composante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.composante')),
            ],
        ),
        migrations.CreateModel(
            name='Probleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_identification', models.DateField()),
                ('source', models.CharField(max_length=255)),
                ('typologie', models.CharField(max_length=255)),
                ('criticite', models.CharField(max_length=255)),
                ('remonter_tdb', models.BooleanField(default=False)),
                ('solution_proposee', models.TextField()),
                ('porteur_solution', models.CharField(max_length=255)),
                ('delai_mise_en_oeuvre', models.CharField(max_length=255)),
                ('statut_solution', models.CharField(max_length=255)),
                ('composante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.composante')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('identifiant', models.CharField(max_length=100)),
                ('axe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.axe')),
                ('portefeuille', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard_app.portefeuille')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=255)),
                ('est_lance', models.BooleanField(default=False)),
                ('ministere_responsable', models.CharField(max_length=255)),
                ('chef_projet', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=20)),
                ('date_lancement', models.DateField(blank=True, null=True)),
                ('duree_mois', models.IntegerField(blank=True, null=True)),
                ('cout', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('financement_public', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('financement_prive', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('financement_ppp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('partenaire_pad', models.TextField(blank=True, null=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.programme')),
            ],
        ),
        migrations.AddField(
            model_name='composante',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.projet'),
        ),
    ]
