# Generated by Django 5.2 on 2025-05-01 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_axe_composante_portefeuille_activite_probleme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portefeuille',
            name='axe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.axe'),
        ),
    ]
