# Generated by Django 5.2 on 2025-05-01 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0005_remove_projet_cout_remove_projet_date_lancement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activite',
            name='est_synthese',
        ),
    ]
