# Generated by Django 5.2 on 2025-05-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0006_remove_activite_est_synthese'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activite',
            name='execution_financiere',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='execution_physique',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='facteurs_explication',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='feu_tricolore',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='statut',
        ),
        migrations.AddField(
            model_name='composante',
            name='Statut_composante',
            field=models.CharField(choices=[('En cours', 'En cours'), ('En cours avec difficulté mineure', 'En cours avec difficulté mineure'), ('En cours avec difficulté majeure', 'En cours avec difficulté majeure'), ('Bloquée', 'Bloquée')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='composante',
            name='facteurs_explication',
            field=models.TextField(blank=True, null=True),
        ),
    ]
