# Generated by Django 5.2 on 2025-05-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0007_remove_activite_execution_financiere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activite',
            name='dec_cible',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='dec_prev_t1',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='dec_prev_t2',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='dec_prev_t3',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='dec_prev_t4',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='dec_reel_t1',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='dec_reel_t2',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='dec_reel_t3',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='dec_reel_t4',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='taux_decaissement',
        ),
        migrations.AddField(
            model_name='composante',
            name='dec_cible',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='composante',
            name='dec_prev_t1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='composante',
            name='dec_prev_t2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='composante',
            name='dec_prev_t3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='composante',
            name='dec_prev_t4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='composante',
            name='dec_reel_t1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='composante',
            name='dec_reel_t2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='composante',
            name='dec_reel_t3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='composante',
            name='dec_reel_t4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='composante',
            name='taux_decaissement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
