# Generated by Django 5.2 on 2025-05-08 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0008_remove_activite_dec_cible_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composante',
            old_name='Statut_composante',
            new_name='composante_Status',
        ),
    ]
