# Generated by Django 5.2 on 2025-05-08 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0009_rename_statut_composante_composante_composante_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composante',
            old_name='composante_Status',
            new_name='etat',
        ),
    ]
