# Generated by Django 4.2.7 on 2025-05-15 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0010_rename_composante_status_composante_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification')], max_length=10)),
                ('champ_modifie', models.CharField(blank=True, max_length=100, null=True)),
                ('ancienne_valeur', models.TextField(blank=True, null=True)),
                ('nouvelle_valeur', models.TextField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.projet')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard_app.user')),
            ],
        ),
    ]
