# Generated by Django 4.2.7 on 2025-05-15 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard_app', '0011_historiqueprojet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiqueprojet',
            options={'ordering': ['-date_action']},
        ),
        migrations.AlterField(
            model_name='historiqueprojet',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historiqueprojet',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
