# Generated by Django 4.2.7 on 2025-05-15 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0012_alter_historiqueprojet_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoriqueProjet',
        ),
    ]
