# Generated by Django 4.2.7 on 2025-05-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0015_historicalprogramme_historicalprobleme_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalComposante',
        ),
    ]
