# Generated by Django 4.2.7 on 2025-05-20 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard_app', '0016_delete_historicalcomposante'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalComposante',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=255)),
                ('localisation', models.CharField(max_length=255)),
                ('tutelle', models.CharField(max_length=255)),
                ('agence_execution', models.CharField(max_length=255)),
                ('date_lancement', models.DateField(blank=True, null=True)),
                ('duree_mois', models.IntegerField(blank=True, null=True)),
                ('cout', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('financement_public', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('financement_prive', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('financement_ppp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('partenaire_pad', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('En cours', 'En cours'), ('Bloquée', 'Bloquée'), ('Terminée', 'Terminée'), ('Dépriorisée', 'Dépriorisée')], max_length=50)),
                ('etat', models.CharField(choices=[('En cours', 'En cours'), ('En cours avec difficulté mineure', 'En cours avec difficulté mineure'), ('En cours avec difficulté majeure', 'En cours avec difficulté majeure'), ('Bloquée', 'Bloquée')], max_length=50, null=True)),
                ('facteurs_explication', models.TextField(blank=True, null=True)),
                ('dec_prev_t1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dec_prev_t2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dec_prev_t3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dec_prev_t4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dec_cible', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dec_reel_t1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dec_reel_t2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dec_reel_t3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dec_reel_t4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('taux_decaissement', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard_app.projet')),
            ],
            options={
                'verbose_name': 'historical composante',
                'verbose_name_plural': 'historical composantes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
