# Generated by Django 4.2.7 on 2025-06-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0018_message_historicalmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprobleme',
            name='criticite',
            field=models.CharField(choices=[('Moyenne', 'Moyenne'), ('Elevée', 'Elevée'), ('Faible', 'Faible')], max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalprobleme',
            name='statut_solution',
            field=models.CharField(choices=[('Clôturé', 'Clôturé'), ('En cours', 'En cours'), ('Ouvert', 'Ouvert')], max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalprobleme',
            name='typologie',
            field=models.CharField(choices=[('Financière', 'Financière'), ('Administratif', 'Administratif'), ('Contractuel', 'Contractuel'), ('Foncier', 'Foncier'), ('Opérationnel', 'Opérationnel'), ('Règlementaire', 'Règlementaire')], max_length=255),
        ),
        migrations.AlterField(
            model_name='probleme',
            name='criticite',
            field=models.CharField(choices=[('Moyenne', 'Moyenne'), ('Elevée', 'Elevée'), ('Faible', 'Faible')], max_length=255),
        ),
        migrations.AlterField(
            model_name='probleme',
            name='statut_solution',
            field=models.CharField(choices=[('Clôturé', 'Clôturé'), ('En cours', 'En cours'), ('Ouvert', 'Ouvert')], max_length=255),
        ),
        migrations.AlterField(
            model_name='probleme',
            name='typologie',
            field=models.CharField(choices=[('Financière', 'Financière'), ('Administratif', 'Administratif'), ('Contractuel', 'Contractuel'), ('Foncier', 'Foncier'), ('Opérationnel', 'Opérationnel'), ('Règlementaire', 'Règlementaire')], max_length=255),
        ),
    ]
