# Generated by Django 4.2.7 on 2025-06-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0019_alter_historicalprobleme_criticite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprobleme',
            name='delai_mise_en_oeuvre',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historicalprobleme',
            name='statut_solution',
            field=models.CharField(choices=[('Cloturé', 'Cloturé'), ('En cours', 'En cours'), ('Ouvert', 'Ouvert')], max_length=255),
        ),
        migrations.AlterField(
            model_name='probleme',
            name='delai_mise_en_oeuvre',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='probleme',
            name='statut_solution',
            field=models.CharField(choices=[('Cloturé', 'Cloturé'), ('En cours', 'En cours'), ('Ouvert', 'Ouvert')], max_length=255),
        ),
    ]
