# Generated by Django 4.2.7 on 2025-06-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0020_alter_historicalprobleme_delai_mise_en_oeuvre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composante',
            name='Fin_prévisionnelle',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcomposante',
            name='Fin_prévisionnelle',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprobleme',
            name='delai_mise_en_oeuvre',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='probleme',
            name='delai_mise_en_oeuvre',
            field=models.DateField(),
        ),
    ]
