# Generated by Django 4.2.7 on 2025-06-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0021_composante_fin_prévisionnelle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprobleme',
            name='date_identification',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprobleme',
            name='delai_mise_en_oeuvre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='probleme',
            name='date_identification',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='probleme',
            name='delai_mise_en_oeuvre',
            field=models.DateField(blank=True, null=True),
        ),
    ]
