# Generated by Django 4.2.7 on 2025-06-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0022_alter_historicalprobleme_date_identification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composante',
            old_name='Fin_prévisionnelle',
            new_name='Fin_previsionnelle',
        ),
        migrations.RenameField(
            model_name='historicalcomposante',
            old_name='Fin_prévisionnelle',
            new_name='Fin_previsionnelle',
        ),
    ]
